name: Conan Package Discovery by Jira Ticket

on:
  workflow_dispatch:
    inputs:
      jira_ticket_number:
        description: 'Jira ticket number for Conan package discovery (e.g., cura_12345)'
        required: true
        type: string

jobs:
  find-packages:
    name: Find packages for Jira ticket
    uses: ultimaker/cura-workflows/.github/workflows/find_package_by_ticket.yml@jira_find_package
    with:
      jira_ticket_number: ${{ inputs.jira_ticket_number }}
    secrets: inherit